#!/bin/sh
# Using external pipe with st, give a dmenu prompt of recent commands,
# allowing the user to copy the output of one.
# xclip required for this script.
# By Jaywalker and Luke
tmpfile=$(mktemp /tmp/st-cmd-output.XXXXXX)
touch /home/owner/dupa
# trap 'rm "$tmpfile"' 0 1 15
sed -n "w $tmpfile"

#HACK: my tmux modeline  starts with λ - remove it
last_line=$(wc -l < "$tmpfile")
awk -v last_line="$last_line" '/^─*$/{next}  /^λ/{if(NR!=last_line){print};next} {print}'  "$tmpfile" > "$tmpfile.bak"
mv "$tmpfile.bak" "$tmpfile"

sed -i 's/\x0//g' "$tmpfile"
ps1="$(grep "\S" "$tmpfile" | tail -n 1 | sed 's/^\s*//' | cut -d' ' -f1)"
chosen="$(grep -F "$ps1" "$tmpfile" | sed '$ d' | tac | dmenu -p "Copy which command's output?" -i -l 10 | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
eps1="$(echo "$ps1" | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
awk "/^$chosen$/{p=1;print;next} p&&/$eps1/{p=0};p" "$tmpfile" | xclip -selection clipboard
